image: inseefrlab/onyxia-rstudio:latest

stages:
  - check
  - deploy

variables:
  GIT_SSL_NO_VERIFY: "1"
  PKG_NAME: "mapvotr"
  HTTP_PROXY: http://proxy-app.insee.fr:3128
  HTTPS_PROXY: http://proxy-app.insee.fr:3128
  NO_PROXY: insee.test,insee.intra,insee.fr,localhost


pkg_check:
  stage: check
  tags:
    - docker
  script:
#   - bash <(curl -s https://gitlab.insee.fr/infrastructure/lss/runner/-/raw/main/ca-certificates.sh)
    - R -e "install.packages(c('logr','vctrs'), repos='https://nexus.insee.fr/repository/r-cran/', method = 'wget', extra = '--no-check-certificate')"
    - Rscript -e 'devtools::check(check_dir = ".",
                                  error_on  = "error",
                                  cran      = FALSE,
                                  document  = FALSE,
                                  manual    = FALSE)'
  artifacts:
    paths:
      - "${PKG_NAME}_*.tar.gz"

pages:
  stage: deploy
  tags:
    - docker
  script:
#   - bash <(curl -s https://gitlab.insee.fr/infrastructure/lss/runner/-/raw/main/ca-certificates.sh)
    - R -e "install.packages(c('logr','vctrs'), repos='https://nexus.insee.fr/repository/r-cran/', method = 'wget', extra = '--no-check-certificate')"
    - Rscript -e "options(pkgdown.internet = FALSE, repos = c(CRAN = 'https://nexus.insee.fr/repository/r-cran/')) ; pkgdown::build_site()"
  artifacts:
    paths:
      - public
  when: manual # pour declencher manuellement le job quand version stable
#  only:
#    - master #indiquer master plus tard

# modele de pkgdown en CI en intranet : https://gitlab.insee.fr/demographie-entreprises/sine/pkg-sine
